fix: upgrade to Swift 6.1 and install Bazelisk binary directly

diff --git a/renovate_image/Dockerfile b/renovate_image/Dockerfile
--- a/renovate_image/Dockerfile
+++ b/renovate_image/Dockerfile
@@ -44,14 +44,17 @@ RUN install-apt libicu-dev
 RUN install-apt build-essential 
 RUN install-apt pkg-config
 
-# Inspired by https://github.com/apple/swift-docker/blob/main/5.8/ubuntu/20.04/Dockerfile
-# pub   4096R/ED3D1561 2019-03-22 [SC] [expires: 2023-03-23]
-#       Key fingerprint = A62A E125 BBBF BB96 A6E0  42EC 925C C1CC ED3D 1561
-# uid                  Swift 5.x Release Signing Key <swift-infrastructure@swift.org
-ARG SWIFT_SIGNING_KEY=A62AE125BBBFBB96A6E042EC925CC1CCED3D1561
+# Inspired by https://github.com/swiftlang/swift-docker/blob/main/6.1/ubuntu/20.04/Dockerfile
+# NOTE: When copying over the latest code, do not install/uninstall curl. It is
+# already part of the base image. Also, it is used later in the build.
+
+# pub   rsa4096 2024-09-16 [SC] [expires: 2026-09-16]
+#      52BB7E3DE28A71BE22EC05FFEF80A866B47A981F
+# uid           [ unknown] Swift 6.x Release Signing Key <swift-infrastructure@forums.swift.org>
+ARG SWIFT_SIGNING_KEY=52BB7E3DE28A71BE22EC05FFEF80A866B47A981F
 ARG SWIFT_PLATFORM=ubuntu20.04
-ARG SWIFT_BRANCH=swift-5.8.1-release
-ARG SWIFT_VERSION=swift-5.8.1-RELEASE
+ARG SWIFT_BRANCH=swift-6.1-release
+ARG SWIFT_VERSION=swift-6.1-RELEASE
 ARG SWIFT_WEBROOT=https://download.swift.org
 
 ENV SWIFT_SIGNING_KEY=$SWIFT_SIGNING_KEY \
@@ -62,7 +65,6 @@ ENV SWIFT_SIGNING_KEY=$SWIFT_SIGNING_KEY \
 
 RUN set -e; \
     ARCH_NAME="$(dpkg --print-architecture)"; \
-    url=; \
     case "${ARCH_NAME##*-}" in \
         'amd64') \
             OS_ARCH_SUFFIX=''; \
@@ -77,24 +79,44 @@ RUN set -e; \
     && SWIFT_SIG_URL="$SWIFT_BIN_URL.sig" \
     # - Download the GPG keys, Swift toolchain, and toolchain signature, and verify.
     && export GNUPGHOME="$(mktemp -d)" \
-    && export SWIFT_DOWNLOAD="$(mktemp -d)" \
-    && cd "${SWIFT_DOWNLOAD}" \
     && curl -fsSL "$SWIFT_BIN_URL" -o swift.tar.gz "$SWIFT_SIG_URL" -o swift.tar.gz.sig \
     && gpg --batch --quiet --keyserver keyserver.ubuntu.com --recv-keys "$SWIFT_SIGNING_KEY" \
     && gpg --batch --verify swift.tar.gz.sig swift.tar.gz \
     # - Unpack the toolchain, set libs permissions, and clean up.
     && tar -xzf swift.tar.gz --directory / --strip-components=1 \
     && chmod -R o+r /usr/lib/swift \
-    && rm -rf "$GNUPGHOME" "${SWIFT_DOWNLOAD}"
+    && rm -rf "$GNUPGHOME" swift.tar.gz.sig swift.tar.gz
 
 # END: Install Swift
 
 # Back to less privileged user
 USER 1000
 
-# Install Bazelisk
-RUN npm install -g @bazel/bazelisk
+# BEGIN: Install Bazelisk
 
+ARG BAZELISK_VERSION=v1.26.0
+
+ENV BAZELISK_VERSION=$BAZELISK_VERSION
+
+# RUN npm install -g @bazel/bazelisk
+RUN set -e -x; \
+    ARCH_NAME="$(dpkg --print-architecture)"; \
+    case "${ARCH_NAME##*-}" in \
+        'amd64') \
+            OS_ARCH_SUFFIX='-amd64'; \
+            ;; \
+        'arm64') \
+            OS_ARCH_SUFFIX='-arm64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac; \
+    BAZELISK_BIN=/usr/local/bin/bazelisk \
+    BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux${OS_ARCH_SUFFIX}" \
+    && pwd \
+    && curl -fsSL "${BAZELISK_URL}" -o "${BAZELISK_BIN}" \
+    && chmod +x "${BAZELISK_BIN}"
+
+# END: Install Bazelisk
 
 # Set required environment variables
 ENV CC=clang
